### ISSUE TITLE
Lab 3 - Arrays Union

### ISSUE THREAD

**Issue by daria-gh** [ArtemDomnikoff/Repository#12]
Let's say you have two arrays:
  ```
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
```

Write a program that returns a union between these arrays (without duplicates).

How it looks?
```
Please input the first array:
>>> 1 1 2 3 5 8 13 21 34 66 89
Please input the second array:
>>> 1 2 3 4 5 6 7 8 9 10 11 12 13
Distinct union is: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 21, 34, 55, 89
```

**Comment by lifesgood-21** [comment]
> Let's say you have two arrays:
> 
> ```
> a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
> b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
> ```
> 
> Write a program that returns an intersection between these arrays (without duplicates).
> 
> How it looks?
> 
> ```
> Please input the first array:
> >>> 1 1 2 3 5 8 13 21 34 66 89
> Please input the second array:
> >>> 1 2 3 4 5 6 7 8 9 10 11 12 13
> Distinct intersection is: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 21, 34, 55, 89
> ```

![WhatsApp Image 2019-10-16 at 13 55 42](https://user-images.githubusercontent.com/17679512/66913429-4989db80-f01d-11e9-95d5-7877b3028985.jpeg)

**Comment by daria-gh** [comment]
Sorry, my mistake. 
Fixed @lifesgood-21
