### ISSUE TITLE
Lab 4 - Alphabet

### ISSUE THREAD

**Issue by lifesgood-21** [ArtemDomnikoff/Repository#14]
Существует  такая  штука,  как  таблица  символов  ASCII, согласно которой ,  любой символ алфавита имеет свой код. В python( и не только ) есть  функция chr(хх),  где хх - некоторое  число,  которая вернет символ из таблицы ASCII, согласно коду.

**Необходимо:**
- [x] Написать функцию, выводящую на экран символы  в заданном диапазоне, в N столбцов.
- [x] Написать функцию, выводящую на экран символы латинского алфавита в N столбцов.
- [x] Написать функцию, выводящую на экран символы кириллического алфавита в N строк.

**Comment by daria-gh** [comment]
@ArtemDomnikoff if you got stuck, please left questions here in comments

**Comment by daria-gh** [comment]
How it should look like in console:
```>>>  - is what user types```

```
Choose ASCII symbols and press enter: 1 - All, 2 - Latin, 3 - Cyrillic. To exit press Ctrl-C.
>>> 2
Choose range.
From: 
>>> 2
To: 
>>> 4
Result:
B C D

Choose ASCII symbols and press enter: 1 - All, 2 - Latin, 3 - Cyrillic. To exit press Ctrl-C.
>>> 1
Choose range:
From: 
>>> 36
To:
>>> 38
Result:
$ % &
```

[See ASCII table](https://upload.wikimedia.org/wikipedia/commons/8/81/Table_ascii_extended.png)

**Comment by lifesgood-21** [comment]
Нужно  привести код в  порядок ,  используй CamelCase,  не  все  переменные  именованы правильно например result_2

**Comment by lifesgood-21** [comment]
Старайся  не  использовать  сырые  значения  как  то  	
range_start = range_start + 1040
range_end = range_end + 1040
ведь  не  сразу  поенятно  что  такое  1040 ,  заведи  константу  или  переменную  отражающую  суть этого  самого  числа (1040)

**Comment by lifesgood-21** [comment]
Все в  порядке ,  основные недостатки  устранены .
